### ISSUE TITLE
0.11.0: recursive_mutex lock failed: Invalid argument. (STD_EXCEPTION)

### ISSUE THREAD

**Issue by lmangani** [chdb-io/chdb#60]
Stock queries are failing with chdb 0.11.0. Here's an example we know works as expected with chdb 0.10.x

#### query
```sql
SELECT
    town,
    district,
    count() AS c,
    round(avg(price)) AS price
FROM url('https://datasets-documentation.s3.eu-west-3.amazonaws.com/house_parquet/house_0.parquet')
GROUP BY
    town,
    district
LIMIT 10
```
#### Failing response
```
Code: 1001. DB::Exception: std::__1::system_error: recursive_mutex lock failed: Invalid argument. (STD_EXCEPTION)
```

#### Expected response

query results

**Comment by auxten** [comment]
I have [fixed the chdb-server](https://github.com/chdb-io/chdb-server/blob/main/main.py#L11), and also some optimization. Run chdb.query without forking new process.

The old implementation will cause deadlock. still not sure if it's the reason cause the recursive_mutex lock failed.

[previous implementation](https://github.com/chdb-io/chdb-server/blob/b722682d935fa588f16e8dea2d5818395550ae9c/main.py) has a bug that causes stderr to block when the pipe buffer is full. The issue I'm experiencing here is getting stuck on the query without a chance to run read_pipe. I suspect that the recursive lock problem reported by clickhouse may be due to the same reason, but we can't confirm it now. Let's wait for @nmreadelf 's debug message.

**Comment by lmangani** [comment]
The error changed but the failure persists:

> Code: 1001. DB::Exception: std::__1::system_error: recursive_mutex lock failed: Invalid argument. (STD_EXCEPTION)

**Comment by auxten** [comment]
It seems another ClickHouse issue. Trying sort out why they do that.
